"""empty message

Revision ID: 641eaf59eb19
Revises: 35d106b2e222
Create Date: 2023-05-08 11:14:21.732517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641eaf59eb19'
down_revision = '35d106b2e222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'restaurant_id')
    # ### end Alembic commands ###
